### ISSUE TITLE
你的项目是移植的apm吗？

### ISSUE THREAD

**Issue by wenguanglee** [ShilinGuo520/flystm32_ardupilot#1]
你移植的apm吗？有试验过吗？
你的硬件是怎样的？
原理图在哪里可以获取到？

**Comment by ShilinGuo520** [comment]
我是基于apm3.2版本进行移植，并且试飞过无数次，与apm一样，比起pixhawk有一定差距
我的硬件原理图、bom、pcb图你可以在我的另一个仓库里获取到链接如下：
https://github.com/ShilinGuo520/maple-lite/tree/master/hardware
如果具体使用方法（软件烧录、调试）可以参考博客：
http://blog.csdn.net/guodaye5200/article/details/68950875

**Comment by wenguanglee** [comment]
感谢回复，
主要差距来自传感器还是CPU资源？

发自我的 iPhone

**Comment by ShilinGuo520** [comment]
主要差距应该来自于算法本身，没有具体研究过，这个stm32f103的版本是基于apm的算法，据说是用的互补滤波（apm原版atmage2560性能问题），pixhawk是采用了卡尔曼滤波，目前来看和传感器关系不太大

**Comment by wenguanglee** [comment]
用missionplanner 进行校准加速度传感器总失败，是这样吗？
另外里面设备类型选择哪种？选apm吗？

**Comment by ShilinGuo520** [comment]
校准失败这是个已知问题，目前还没有好得解决办法，你可以直接将解锁的检查跳过，这样就可以上天飞了，使用默认得校准就可以飞，当然如果你发现了好得解决方案，欢迎提交过来

**Comment by ShilinGuo520** [comment]
你指得设备类型是什么意思呢？

**Comment by wenguanglee** [comment]
在使用missionplan的设置的时候，可以选择你的硬件系统是pix还是apm。

**Comment by ShilinGuo520** [comment]
这个建议不用设置，设置后有什么不兼容具体不清楚
