### ISSUE TITLE
关于晶振

### ISSUE THREAD

**Issue by seishinkouki** [ShilinGuo520/flystm32_ardupilot#2]
你用的应该是12MHz无源晶振吧, 而不是pcb上封装的16MHz
![image](https://cloud.githubusercontent.com/assets/8842321/26758362/303ca878-490e-11e7-8e89-e7833b382938.png)

**Comment by ShilinGuo520** [comment]
是的，晶体使用的是12Mhz无源晶体，在设计pcb时，标注了16M，stm32f103最高频率72Mhz，代码里很大地方都是按照这个标准来进行设计，使用16Mhz无法倍频到72Mhz，所以修改为12Mhz，这个在readme文件有提到，当然使用8Mhz也是没有问题，PLL改为9即可，修改方法参考想要的commit

**Comment by wenguanglee** [comment]
如果修改为8M，需要改动哪个文件的PLL值？

**Comment by ShilinGuo520** [comment]
你可以参考这个提交：
90ecd17823091bf15e07f1a0bead99297502ef35
